Q3A_FLAGS = -DGAME_Q3A
RTCWMP_FLAGS = -DGAME_RTCWMP
JAMP_FLAGS = -DGAME_JAMP
JK2MP_FLAGS = -DGAME_JK2MP
RTCWSP_FLAGS = -DGAME_RTCWSP
WET_FLAGS = -DGAME_WET

BINARY = stub_qmm
SRC_FILES = main.cpp
HDR_FILES = version.h
